version: '3.2'

services:
   para:
     image: erudikaltd/para
     ports:
       - "8090:8090"
     volumes:
       - type: volume
         source: paraData
         target: /para/data
       - type: volume
         source: paraLib
         target: /para/lib
       - type: bind
         source: ./para-application.conf
         target: /para/application.conf
     restart: always
     env_file: para.env

   scoold:
     depends_on:
       - para
     build: .
     ports:
       - "8091:8091"
     volumes:
       - type: bind
         source: ./scoold-application.conf
         target: /scoold/application.conf
     restart: always
     env_file: scoold.env
volumes:
  paraData:
  paraLib: